config/routes.rb
Rails.application.routes.draw do
  resources :magazines
  resources :oenologists
  devise_for :users
  resources :strains
  resources :wines
  root 'wines#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/wine.rb
class Wine < ApplicationRecord
    has_many :wine_strains, dependent: :destroy
    has_many :strains, through: :wine_strains
    accepts_nested_attributes_for :wine_strains, reject_if: :all_blank 
    has_many :wine_scores, dependent: :destroy
    has_many :oenologists, through: :wine_scores
    accepts_nested_attributes_for :wine_scores, reject_if: :all_blank 
end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
  before_action :set_wine, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :not_admin, except: :index

  # GET /wines or /wines.json
  def index
    @wines = Wine.all
    @strains = Strain.all
    @oenologists = Oenologist.all
  end

  # GET /wines/1 or /wines/1.json
  def show
  end

  # GET /wines/new
  def new
    @wine = Wine.new
    @strains = Strain.order('name ASC')
    @wine.wine_strains.build
  end

  # GET /wines/1/edit
  def edit
    @oenologists = Oenologist.all
    @strains = Strain.all
    @wine = Wine.find(params[:id])
  end

  # POST /wines or /wines.json
  def create
    @wine = Wine.new(wine_params)

    respond_to do |format|
      if @wine.save
        format.html { redirect_to @wine, notice: "Wine was successfully created." }
        format.json { render :show, status: :created, location: @wine }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wines/1 or /wines/1.json
  def update
    respond_to do |format|
      if @wine.update(wine_params)
        format.html { redirect_to @wine, notice: "Wine was successfully updated." }
        format.json { render :show, status: :ok, location: @wine }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wines/1 or /wines/1.json
  def destroy
    @wine.destroy
    respond_to do |format|
      format.html { redirect_to wines_url, notice: "Wine was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wine
      @wine = Wine.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def wine_params
      params.require(:wine).permit(:name, wine_strains_attributes: [:strain_id, :percentage], wine_scores_attributes: [:oenologist_id, :score])
    end

    def not_admin
      redirect_to root_path, alert: "You'r not an admin." and return if !current_user.admin
    end
end

app/helpers/wines_helper.rb
module WinesHelper
end

app/views/wines/_form.html.erb
<%= form_with(model: wine, local: true) do |form| %>
  <% if wine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wine.errors.count, "error") %> prohibited this wine from being saved:</h2>

      <ul>
      <% wine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year %>
  </div>

  <br>

  <div class="links">
    <%= link_to_add_association 'Add an strain', form, :wine_strains %>
  </div>

  <br>

  <% if @wine.id != nil %>
    <div class="links">
      <%= link_to_add_association 'Add score', form, :wine_scores %>
    </div>
  <% end %>

  <br>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/wines/_wine_score_fields.html.erb
<div class="field">
    <%= f.label :oenologist_id %>
    <%= f.collection_select :oenologist_id, @oenologists, :id, :name %>
</div>
<div class="field">
    <%= f.label :score %>
    <%= f.number_field :score %>
</div>

app/views/wines/_wine_strain_fields.html.erb
<div class="field">
    <%= f.label :strain_id %>
    <%= f.collection_select :strain_id, @strains, :id, :name %>
</div>
<div class="field">
    <%= f.label :percentage %>
    <%= f.text_field :percentage %>
</div>

app/views/wines/edit.html.erb
<h1>Editing Wine</h1>

<%= render 'form', wine: @wine %>

<%= link_to 'Show', @wine %> |
<%= link_to 'Back', wines_path %>

app/views/wines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wines</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Strains</th>
      <th>Scores</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wines.each do |wine| %>
      <tr>
        <td><%= wine.name %></td>
        <td>
            <% wine_strains = wine.wine_strains %>
            <% strains = wine_strains.map do |wine_strain| %>
              <% [Strain.find(wine_strain.strain_id).name, wine_strain.percentage] %>
            <% end %>
            <ul>
              <% strains.sort.each do |strain| %>
                <li><%= strain.first %>(<%= strain.second %>%)</li>
              <% end %>
            </ul>
          </ul>
        </td>
        <td>
          <% wine_scores = wine.wine_scores %>
          <% scores = wine_scores.map do |wine_score| %>
            <% [Oenologist.find(wine_score.oenologist_id).name, wine_score.score, Oenologist.find(wine_score.oenologist_id).age] %>
          <% end %>
          <ul>
            <% scores.sort_by { |obj| obj.third }.each do |score| %>
              <li><%= score.first %>(<%= score.second %>)</li>
            <% end %>
          </ul>
        </td>

        <% if current_user.email == "peter@gmail.com" %>
          <td><%= link_to 'Show', wine %></td>
          <td><%= link_to 'Edit', edit_wine_path(wine) %></td>
          <td><%= link_to 'Destroy', wine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if current_user.email == "peter@gmail.com" %>
  <%= link_to 'New Wine', new_wine_path %>
<% end %>

app/views/wines/new.html.erb
<h1>New Wine</h1>

<%= render 'form', wine: @wine %>

<%= link_to 'Back', wines_path %>

app/views/wines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @wine.name %>
</p>

<%= link_to 'Edit', edit_wine_path(@wine) %> |
<%= link_to 'Back', wines_path %>